#!/bin/bash
# Unraid installer for virtio-mem-balancer.
#
# Creates a per-domain User Scripts entry under:
#   /boot/config/plugins/user.scripts/scripts/virtio-mem-balancer-<domain>/
#
# After running, open Settings -> User Scripts in the Unraid web UI and set
# the schedule to "At First Array Start Only".
#
# Usage: ./install.sh <libvirt-domain-name>
# Re-run to refresh balancer.sh from the repo; your config file is preserved.

set -euo pipefail

DOMAIN="${1:-}"
if [[ -z "$DOMAIN" ]]; then
    echo "Usage: $0 <libvirt-domain-name>" >&2
    exit 2
fi

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
BALANCER_SRC="$REPO_ROOT/balancer.sh"

if [[ ! -f "$BALANCER_SRC" ]]; then
    echo "ERROR: balancer.sh not found at $BALANCER_SRC" >&2
    echo "       Run this script from inside the cloned repo." >&2
    exit 1
fi

USER_SCRIPTS_BASE="/boot/config/plugins/user.scripts/scripts"
if [[ ! -d "$USER_SCRIPTS_BASE" ]]; then
    echo "ERROR: User Scripts plugin not found at $USER_SCRIPTS_BASE" >&2
    echo "       Install it via Community Applications first." >&2
    exit 1
fi

if ! command -v virsh >/dev/null; then
    echo "ERROR: virsh not found — is this actually the Unraid host?" >&2
    exit 1
fi

if ! virsh domstate "$DOMAIN" >/dev/null 2>&1; then
    echo "WARNING: libvirt domain '$DOMAIN' not found. Proceeding anyway — make sure the VM exists before enabling the script."
fi

TARGET_DIR="$USER_SCRIPTS_BASE/virtio-mem-balancer-$DOMAIN"
CONFIG_PATH="$TARGET_DIR/balancer.conf"
BALANCER_PATH="$TARGET_DIR/balancer.sh"
WRAPPER_PATH="$TARGET_DIR/script"

mkdir -p "$TARGET_DIR"

# Always refresh the balancer itself so `git pull + re-run` picks up fixes.
# -m 0755 is a hint only; /boot is FAT32 and can't preserve it.
install -m 0755 "$BALANCER_SRC" "$BALANCER_PATH"

# Preserve an existing config; seed a new one if absent.
if [[ ! -f "$CONFIG_PATH" ]]; then
    cat >"$CONFIG_PATH" <<EOF
# virtio-mem-balancer config for domain: $DOMAIN
# Edit and save — User Scripts will re-read on next run.

DOMAIN="$DOMAIN"
MAX_KIB=6291456     # pluggable ceiling (6 GiB)
STEP_KIB=524288     # grow/shrink step (512 MiB)
LOW_PCT=15          # grow when guest unused% < this
HIGH_PCT=40         # shrink when guest unused% > this
INTERVAL=15         # seconds between ticks
NODE=0              # virtio-mem NUMA node
EOF
    echo "Wrote default config: $CONFIG_PATH"
else
    echo "Kept existing config:  $CONFIG_PATH"
fi

# Wrapper that User Scripts actually runs. Points at the adjacent config/balancer.
# /boot is FAT32 and can't store the +x bit, so balancer.sh is invoked via
# `bash` explicitly. User Scripts itself runs this wrapper via `sh -c`.
cat >"$WRAPPER_PATH" <<EOF
#!/bin/bash
# Auto-generated by virtio-mem-balancer/unraid/install.sh
# Domain: $DOMAIN
HERE="\$(dirname "\$(readlink -f "\$0")")"
# When User Scripts stages this into /tmp, follow the original /boot copy.
if [[ "\$HERE" != /boot/* ]]; then
    HERE="$TARGET_DIR"
fi
export CONFIG="\$HERE/balancer.conf"
exec bash "\$HERE/balancer.sh"
EOF
chmod +x "$WRAPPER_PATH" 2>/dev/null || true

echo "virtio-mem balancer ($DOMAIN)" >"$TARGET_DIR/name"
cat >"$TARGET_DIR/description" <<EOF
Auto-grow/shrink the '$DOMAIN' guest's memory via virtio-mem, driven by guest
memory pressure. Self-looping; schedule "At First Array Start Only".
Config: $CONFIG_PATH
Log (tmpfs): /tmp/user.scripts/tmpScripts/virtio-mem-balancer-$DOMAIN/log.txt
EOF

# Verify all four files User Scripts expects are present and non-empty.
missing=()
for f in script name description balancer.sh balancer.conf; do
    if [[ ! -s "$TARGET_DIR/$f" ]]; then
        missing+=("$f")
    fi
done
if (( ${#missing[@]} > 0 )); then
    echo "ERROR: the following files were not created (or are empty): ${missing[*]}" >&2
    echo "       Target: $TARGET_DIR" >&2
    exit 1
fi

cat <<EOF

Installed at: $TARGET_DIR
  script          $(stat -c '%A %s bytes' "$TARGET_DIR/script")
  name            $(stat -c '%A %s bytes' "$TARGET_DIR/name")       -> $(cat "$TARGET_DIR/name")
  description     $(stat -c '%A %s bytes' "$TARGET_DIR/description")
  balancer.sh     $(stat -c '%A %s bytes' "$TARGET_DIR/balancer.sh")
  balancer.conf   $(stat -c '%A %s bytes' "$TARGET_DIR/balancer.conf")

Next steps:
  1. In Unraid web UI: Settings -> User Scripts
  2. Find "virtio-mem balancer ($DOMAIN)"
  3. Set its schedule to "At First Array Start Only" and click Apply
  4. Click "Run Script" once now to launch the daemon immediately
     (it self-loops — one invocation per boot is enough)

Edit $CONFIG_PATH any time; kill and relaunch to apply:
  pkill -f "virtio-mem-balancer-$DOMAIN/balancer.sh"
  rm -f /var/run/virtio-mem-balancer.$DOMAIN.lock

Prerequisites to verify BEFORE running:
  - VM XML has <maxMemory>, <numa>, and <memory model='virtio-mem'> (see README.md)
  - Guest kernel cmdline includes: memhp_default_state=online_kernel

EOF
